export const RADIUS = 120;
export const COLOR_BG = '#E3E3E3';
export const THEME_GREEN = '#24BF9C';
export const THEME_DARK_GREEN = '#136b55';
export const MEDIUM_GREY = '#d3d3d3';
export const DARK_GREY = 'rgba(0, 0, 0, 0.5)';
export const BLACK = '#000';
export const COLOR_FG = THEME_GREEN;
export const PI = 3.14;
